name: Update LoL Stats

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'update_lol_stats.py'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install requests
      
      - name: Update README with LoL stats
        env:
          RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
        run: |
          python update_lol_stats.py
      
      - name: Commit and push if changed
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "📉 Update embarrassing LoL stats" && git push)